    SELECT T_SURVEYOPT.SURVEY_OPT_URL AS SURVEY_RANK_THIRD
    FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-52'
    ) AS T_SURVEYUID
    INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
    INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
    WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
    GROUP BY T_SURVEYOPT.SURVEY_OPT_URL
    ORDER BY COUNT(*) DESC
    LIMIT 3;
    

    SELECT T_SURVEYOPT.SURVEY_OPT_URL AS SURVEY_RANK_SECOND
    FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-53'
    ) AS T_SURVEYUID
    INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
    INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
    WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
    GROUP BY T_SURVEYOPT.SURVEY_OPT_URL
    ORDER BY COUNT(*) DESC
    LIMIT 3;


    SELECT T_SURVEYOPT.SURVEY_OPT_URL AS SURVEY_RANK_THIRD
    FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-52'
    ) AS T_SURVEYUID
    INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
    INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
    WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
    GROUP BY T_SURVEYOPT.SURVEY_OPT_URL
    ORDER BY COUNT(*) DESC
    LIMIT 3;

    
    
