    -- 식욕억제 1순위 
SELECT T_SURVEYOPT.SURVEY_OPT
FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-54'
) AS T_SURVEYUID
INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
GROUP BY T_SURVEYOPT.SURVEY_OPT
ORDER BY COUNT(*) DESC
LIMIT 1 OFFSET 0;
    

-- 식욕억제 2순위 
SELECT T_SURVEYOPT.SURVEY_OPT
FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-54'
) AS T_SURVEYUID
INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
GROUP BY T_SURVEYOPT.SURVEY_OPT
ORDER BY COUNT(*) DESC
LIMIT 1 OFFSET 1;


-- 식욕억제 3순위 
SELECT T_SURVEYOPT.SURVEY_OPT
FROM (
    SELECT T_SURVEY.SURVEY_UID
    FROM SURVEY AS T_SURVEY
    INNER JOIN SURVEYRESULT AS T_SURVEYRESULT ON T_SURVEY.SURVEY_UID = T_SURVEYRESULT.SURVEY_UID
    WHERE T_SURVEY.SURVEY_OPT_ID = 'O-54'
) AS T_SURVEYUID
INNER JOIN SURVEY AS T_SURVEY2 ON T_SURVEYUID.SURVEY_UID = T_SURVEY2.SURVEY_UID
INNER JOIN SURVEY_OPT AS T_SURVEYOPT ON T_SURVEYOPT.SURVEY_OPT_ID = T_SURVEY2.SURVEY_OPT_ID
WHERE T_SURVEY2.SURVEY_QUESTION_ID = 'Q-06'
GROUP BY T_SURVEYOPT.SURVEY_OPT
ORDER BY COUNT(*) DESC
LIMIT 1 OFFSET 2;


    
    
