
CREATE TABLE CATEGORY
(
  CATEGORY_ID VARCHAR(50)  NOT NULL COMMENT '카테고리UID',
  CATEGORY    VARCHAR(100) NOT NULL COMMENT '카데고리',
  PRIMARY KEY (CATEGORY_ID)
) COMMENT '카테고리';

CREATE TABLE COMMUNITY
(
  COMMUNITY_ID      VARCHAR(100) NOT NULL COMMENT '커뮤니티UID',
  COMMUNITY_TITLE   VARCHAR(100) NOT NULL COMMENT '게시글제목',
  COMMUNITY_CONTENT VARCHAR(500) NOT NULL COMMENT '게시글내용',
  COMMUNITY_DATE    VARCHAR(100) NOT NULL COMMENT '게시글작성일',
  CATEGORY_ID       VARCHAR(50)  NOT NULL COMMENT '카테고리UID',
  PRIMARY KEY (COMMUNITY_ID)
) COMMENT '커뮤니티';

ALTER TABLE COMMUNITY
  ADD CONSTRAINT FK_CATEGORY_TO_COMMUNITY
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY (CATEGORY_ID);
