
CREATE TABLE BMI
(
  BMI_UID    VARCHAR(50) NOT NULL COMMENT 'BMI _UID',
  ID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  GENDER_UID VARCHAR(50) NOT NULL COMMENT '성별_UID',
  HEIGHT     VARCHAR(50) NOT NULL COMMENT '신장',
  WEIGHT     VARCHAR(50) NOT NULL COMMENT '체중',
  BMI_RESULT VARCHAR(50) NOT NULL COMMENT 'BMI 결과값',
  PRIMARY KEY (BMI_UID)
);

CREATE TABLE GENDER
(
  GENDER_UID VARCHAR(50) NOT NULL COMMENT '성별_UID',
  GENDER     VARCHAR(50) NOT NULL COMMENT '성별',
  PRIMARY KEY (GENDER_UID)
) COMMENT '성별';

CREATE TABLE MEMBERS
(
  ID          VARCHAR(50) NOT NULL COMMENT '회원아이디',
  NAME        VARCHAR(50) NOT NULL COMMENT '이름',
  GENDER_UID  VARCHAR(50) NOT NULL COMMENT '성별_UID',
  PASSWORD    VARCHAR(50) NOT NULL COMMENT '비밀번호',
  PHONENUMBER VARCHAR(50) NOT NULL COMMENT '연락처',
  ADDRESS     VARCHAR(50) NOT NULL COMMENT '주소',
  EMAIL       VARCHAR(50) NOT NULL COMMENT '이메일',
  PRIMARY KEY (ID)
) COMMENT '회원';

ALTER TABLE BMI
  ADD CONSTRAINT FK_MEMBERS_TO_BMI
    FOREIGN KEY (ID)
    REFERENCES MEMBERS (ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_TO_MEMBERS
    FOREIGN KEY (GENDER_UID)
    REFERENCES GENDER (GENDER_UID);

ALTER TABLE BMI
  ADD CONSTRAINT FK_GENDER_TO_BMI
    FOREIGN KEY (GENDER_UID)
    REFERENCES GENDER (GENDER_UID);

